In [17]:
import pandas as pd
import numpy as np

In [18]:
schoolinfo = pd.read_csv('england_school_information.csv')

In [19]:
schoolinfo

,URN,LANAME,LA,ESTAB,LAESTAB,SCHNAME,STREET,LOCALITY,ADDRESS3,TOWN,...,ISPRIMARY,ISSECONDARY,ISPOST16,AGELOW,AGEHIGH,GENDER,RELCHAR,ADMPOL,OFSTEDRATING,OFSTEDLASTINSP
0,100000,City of London,201,3614,2013614,The Aldgate School,St James's Passage,Duke's Place,NaN,London,...,1,0,0,3.0,11.0,Mixed,Church of England,Not applicable,Outstanding,19-04-2013
1,100001,City of London,201,6005,2016005,City of London School for Girls,St Giles' Terrace,Barbican,NaN,London,...,1,1,1,7.0,18.0,Mixed,None,Selective,NaN,NaN
2,100002,City of London,201,6006,2016006,St Paul's Cathedral School,2 New Change,NaN,NaN,London,...,1,1,0,4.0,13.0,Mixed,Church of England,Not applicable,NaN,NaN
3,100003,City of London,201,6007,2016007,City of London School,107 Queen Victoria Street,NaN,NaN,London,...,1,1,1,10.0,18.0,Boys,None,Not applicable,NaN,NaN
4,100008,Camden,202,2019,2022019,Argyle Primary School,Tonbridge Street,NaN,NaN,London,...,1,0,0,3.0,11.0,Mixed,Does not apply,Not applicable,Good,30-01-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26409,149483,Birmingham,330,2210,3302210,Highters Heath Community School,Highters Heath Lane,Kings Heath,NaN,Birmingham,...,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable,NaN,NaN
26410,149501,Lincolnshire,925,5215,9255215,Old Leake Primary Academy,Old Main Road,Old Leake,NaN,Boston,...,1,0,0,3.0,11.0,Mixed,None,Not applicable,NaN,NaN
26411,149530,Liverpool,341,4014,3414014,Dixons Croxteth Academy,Carr Lane East,Croxteth,NaN,Liverpool,...,0,1,1,11.0,18.0,NaN,Does not apply,NaN,NaN,NaN
26412,149531,Calderdale,381,4008,3814008,The Brooksbank School,Victoria Road,NaN,NaN,Elland,...,0,1,1,11.0,18.0,Mixed,Does not apply,NaN,NaN,NaN
26413,149532,Cornwall,908,2055,9082055,Grampound-with-Creed Primary School,Fore Street,Grampound,NaN,Truro,...,1,0,0,2.0,11.0,Mixed,Church of England,NaN,NaN,NaN

In [32]:
schoolinfo["POSTCODE"].isna().sum()

35

In [20]:
schoolinfo["lat"] = np.nan

In [21]:
schoolinfo["long"] = np.nan

In [22]:
schoolinfo.set_index('POSTCODE', inplace=True,drop=False)

In [23]:
import os
folder_files = os.listdir(r'postcodes') 
print("This Folder contains {len_folder} file(s).".format(len_folder=len(folder_files)))
filepath = (r'postcodes')
for file in folder_files:
    print(os.path.join(filepath, file))
    #print(file_name)
    file_name = os.path.join(filepath, file)
    postcodefile = pd.read_csv(file_name)
    poscodes = postcodefile.loc[postcodefile['Postcode'].isin(schoolinfo.index)]
    schoolinfo.update(poscodes.set_index('Postcode'))
    #print(filename)

This Folder contains 124 file(s).
postcodes\AB.csv
postcodes\AL.csv
postcodes\B.csv
postcodes\BA.csv
postcodes\BB.csv
postcodes\BD.csv
postcodes\BH.csv
postcodes\BL.csv
postcodes\BN.csv
postcodes\BR.csv
postcodes\BS.csv
postcodes\BT.csv
postcodes\CA.csv
postcodes\CB.csv
postcodes\CF.csv
postcodes\CH.csv
postcodes\CM.csv
postcodes\CO.csv
postcodes\CR.csv
postcodes\CT.csv
postcodes\CV.csv
postcodes\CW.csv
postcodes\DA.csv
postcodes\DD.csv
postcodes\DE.csv
postcodes\DG.csv
postcodes\DH.csv
postcodes\DL.csv
postcodes\DN.csv
postcodes\DT.csv
postcodes\DY.csv
postcodes\E.csv
postcodes\EC.csv
postcodes\EH.csv
postcodes\EN.csv
postcodes\EX.csv
postcodes\FK.csv
postcodes\FY.csv
postcodes\G.csv
postcodes\GL.csv
postcodes\GU.csv
postcodes\GY.csv
postcodes\HA.csv
postcodes\HD.csv
postcodes\HG.csv
postcodes\HP.csv
postcodes\HR.csv
postcodes\HS.csv
postcodes\HU.csv
postcodes\HX.csv
postcodes\IG.csv
postcodes\IM.csv
postcodes\IP.csv
postcodes\IV.csv
postcodes\JE.csv
postcodes\KA.csv
postcodes\KT.csv
postcodes\KW.csv
postcodes\KY.csv
postcodes\L.csv
postcodes\LA.csv
postcodes\LD.csv
postcodes\LE.csv
postcodes\LL.csv
postcodes\LN.csv
postcodes\LS.csv
postcodes\LU.csv
postcodes\M.csv
postcodes\ME.csv
postcodes\MK.csv
postcodes\ML.csv
postcodes\N.csv
postcodes\NE.csv
postcodes\NG.csv
postcodes\NN.csv
postcodes\NP.csv
postcodes\NR.csv
postcodes\NW.csv
postcodes\OL.csv
postcodes\OX.csv
postcodes\PA.csv
postcodes\PE.csv
postcodes\PH.csv
postcodes\PL.csv
postcodes\PO.csv
postcodes\PR.csv
postcodes\RG.csv
postcodes\RH.csv
postcodes\RM.csv
postcodes\S.csv
postcodes\SA.csv
postcodes\SE.csv
postcodes\SG.csv
postcodes\SK.csv
postcodes\SL.csv
postcodes\SM.csv
postcodes\SN.csv
postcodes\SO.csv
postcodes\SP.csv
postcodes\SR.csv
postcodes\SS.csv
postcodes\ST.csv
postcodes\SW.csv
postcodes\SY.csv
postcodes\TA.csv
postcodes\TD.csv
postcodes\TF.csv
postcodes\TN.csv
postcodes\TQ.csv
postcodes\TR.csv
postcodes\TS.csv
postcodes\TW.csv
postcodes\UB.csv
postcodes\W.csv
postcodes\WA.csv
postcodes\WC.csv
postcodes\WD.csv
postcodes\WF.csv
postcodes\WN.csv
postcodes\WR.csv
postcodes\WS.csv
postcodes\WV.csv
postcodes\YO.csv
postcodes\ZE.csv

In [24]:
schoolinfo

,URN,LANAME,LA,ESTAB,LAESTAB,SCHNAME,STREET,LOCALITY,ADDRESS3,TOWN,...,ISPOST16,AGELOW,AGEHIGH,GENDER,RELCHAR,ADMPOL,OFSTEDRATING,OFSTEDLASTINSP,lat,long
POSTCODE,,,,,,,,,,,,,,,,,,,,,
EC3A 5DE,100000,City of London,201,3614,2013614,The Aldgate School,St James's Passage,Duke's Place,NaN,London,...,0,3.0,11.0,Mixed,Church of England,Not applicable,Outstanding,19-04-2013,NaN,NaN
EC2Y 8BB,100001,City of London,201,6005,2016005,City of London School for Girls,St Giles' Terrace,Barbican,NaN,London,...,1,7.0,18.0,Mixed,None,Selective,NaN,NaN,NaN,NaN
EC4M 9AD,100002,City of London,201,6006,2016006,St Paul's Cathedral School,2 New Change,NaN,NaN,London,...,0,4.0,13.0,Mixed,Church of England,Not applicable,NaN,NaN,NaN,NaN
EC4V 3AL,100003,City of London,201,6007,2016007,City of London School,107 Queen Victoria Street,NaN,NaN,London,...,1,10.0,18.0,Boys,None,Not applicable,NaN,NaN,NaN,NaN
WC1H 9EG,100008,Camden,202,2019,2022019,Argyle Primary School,Tonbridge Street,NaN,NaN,London,...,0,3.0,11.0,Mixed,Does not apply,Not applicable,Good,30-01-2019,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B14 4LY,149483,Birmingham,330,2210,3302210,Highters Heath Community School,Highters Heath Lane,Kings Heath,NaN,Birmingham,...,0,4.0,11.0,Mixed,Does not apply,Not applicable,NaN,NaN,52.41098,-1.87300
PE22 9HR,149501,Lincolnshire,925,5215,9255215,Old Leake Primary Academy,Old Main Road,Old Leake,NaN,Boston,...,0,3.0,11.0,Mixed,None,Not applicable,NaN,NaN,NaN,NaN
L11 4SG,149530,Liverpool,341,4014,3414014,Dixons Croxteth Academy,Carr Lane East,Croxteth,NaN,Liverpool,...,1,11.0,18.0,NaN,Does not apply,NaN,NaN,NaN,53.44747,-2.90687
HX5 0QG,149531,Calderdale,381,4008,3814008,The Brooksbank School,Victoria Road,NaN,NaN,Elland,...,1,11.0,18.0,Mixed,Does not apply,NaN,NaN,NaN,53.68124,-1.84900
TR2 4SB,149532,Cornwall,908,2055,9082055,Grampound-with-Creed Primary School,Fore Street,Grampound,NaN,Truro,...,0,2.0,11.0,Mixed,Church of England,NaN,NaN,NaN,50.29866,-4.90173

In [28]:
schoolinfo["lat"].isna().sum()

11588

In [29]:
schoolinfo["long"].isna().sum()

11588

In [34]:
schoolinfo["POSTCODE2"] = schoolinfo["POSTCODE"].str.split(' ').str.join('').copy()

In [35]:
schoolinfo.set_index('POSTCODE2', inplace=True,drop=False)

In [37]:
import os
folder_files = os.listdir(r'postcodes') 
print("This Folder contains {len_folder} file(s).".format(len_folder=len(folder_files)))
filepath = (r'postcodes')
for file in folder_files:
    print(os.path.join(filepath, file))
    #print(file_name)
    file_name = os.path.join(filepath, file)
    postcodefile = pd.read_csv(file_name)
    poscodes = postcodefile.loc[postcodefile['Postcode'].isin(schoolinfo.index)]
    schoolinfo.update(poscodes.set_index('Postcode'))

This Folder contains 124 file(s).
postcodes\AB.csv
postcodes\AL.csv
postcodes\B.csv
postcodes\BA.csv
postcodes\BB.csv
postcodes\BD.csv
postcodes\BH.csv
postcodes\BL.csv
postcodes\BN.csv
postcodes\BR.csv
postcodes\BS.csv
postcodes\BT.csv
postcodes\CA.csv
postcodes\CB.csv
postcodes\CF.csv
postcodes\CH.csv
postcodes\CM.csv
postcodes\CO.csv
postcodes\CR.csv
postcodes\CT.csv
postcodes\CV.csv
postcodes\CW.csv
postcodes\DA.csv
postcodes\DD.csv
postcodes\DE.csv
postcodes\DG.csv
postcodes\DH.csv
postcodes\DL.csv
postcodes\DN.csv
postcodes\DT.csv
postcodes\DY.csv
postcodes\E.csv
postcodes\EC.csv
postcodes\EH.csv
postcodes\EN.csv
postcodes\EX.csv
postcodes\FK.csv
postcodes\FY.csv
postcodes\G.csv
postcodes\GL.csv
postcodes\GU.csv
postcodes\GY.csv
postcodes\HA.csv
postcodes\HD.csv
postcodes\HG.csv
postcodes\HP.csv
postcodes\HR.csv
postcodes\HS.csv
postcodes\HU.csv
postcodes\HX.csv
postcodes\IG.csv
postcodes\IM.csv
postcodes\IP.csv
postcodes\IV.csv
postcodes\JE.csv
postcodes\KA.csv
postcodes\KT.csv
postcodes\KW.csv
postcodes\KY.csv
postcodes\L.csv
postcodes\LA.csv
postcodes\LD.csv
postcodes\LE.csv
postcodes\LL.csv
postcodes\LN.csv
postcodes\LS.csv
postcodes\LU.csv
postcodes\M.csv
postcodes\ME.csv
postcodes\MK.csv
postcodes\ML.csv
postcodes\N.csv
postcodes\NE.csv
postcodes\NG.csv
postcodes\NN.csv
postcodes\NP.csv
postcodes\NR.csv
postcodes\NW.csv
postcodes\OL.csv
postcodes\OX.csv
postcodes\PA.csv
postcodes\PE.csv
postcodes\PH.csv
postcodes\PL.csv
postcodes\PO.csv
postcodes\PR.csv
postcodes\RG.csv
postcodes\RH.csv
postcodes\RM.csv
postcodes\S.csv
postcodes\SA.csv
postcodes\SE.csv
postcodes\SG.csv
postcodes\SK.csv
postcodes\SL.csv
postcodes\SM.csv
postcodes\SN.csv
postcodes\SO.csv
postcodes\SP.csv
postcodes\SR.csv
postcodes\SS.csv
postcodes\ST.csv
postcodes\SW.csv
postcodes\SY.csv
postcodes\TA.csv
postcodes\TD.csv
postcodes\TF.csv
postcodes\TN.csv
postcodes\TQ.csv
postcodes\TR.csv
postcodes\TS.csv
postcodes\TW.csv
postcodes\UB.csv
postcodes\W.csv
postcodes\WA.csv
postcodes\WC.csv
postcodes\WD.csv
postcodes\WF.csv
postcodes\WN.csv
postcodes\WR.csv
postcodes\WS.csv
postcodes\WV.csv
postcodes\YO.csv
postcodes\ZE.csv

In [38]:
schoolinfo["lat"].isna().sum()

48

In [39]:
schoolinfo["long"].isna().sum()

48

In [45]:
girlschool = schoolinfo[(schoolinfo['ISSECONDARY'] == 1)& (schoolinfo['GENDER'] == 'Girls') & (schoolinfo["MINORGROUP"]== "Academy")]

In [46]:
girlschool

,URN,LANAME,LA,ESTAB,LAESTAB,SCHNAME,STREET,LOCALITY,ADDRESS3,TOWN,...,AGELOW,AGEHIGH,GENDER,RELCHAR,ADMPOL,OFSTEDRATING,OFSTEDLASTINSP,lat,long,POSTCODE2
POSTCODE2,,,,,,,,,,,,,,,,,,,,,
SE163TZ,131747,Southwark,210,6907,2106907,Harris Academy Bermondsey,55 Southwark Park Road,NaN,NaN,London,...,11.0,18.0,Girls,Does not apply,Non-selective,Outstanding,19-03-2015,51.49325,-0.07092,SE163TZ
SE220NR,132711,Southwark,210,6908,2106908,Harris Girls' Academy East Dulwich,Homestall Road,NaN,NaN,London,...,11.0,18.0,Girls,Does not apply,Non-selective,Outstanding,15-03-2012,51.45750,-0.05497,SE220NR
L83TF,135174,Liverpool,341,6907,3416907,The Belvedere Academy,17 Belvidere Road,Princes Park,NaN,Liverpool,...,11.0,19.0,Girls,Does not apply,Non-selective,Outstanding,30-01-2015,53.38507,-2.95726,L83TF
BS65RD,135581,"Bristol, City of",801,6909,8016909,Montpelier High School,Cheltenham Road,NaN,NaN,Bristol,...,11.0,18.0,Girls,Does not apply,Non-selective,Serious Weaknesses,24-03-2022,51.46775,-2.59122,BS65RD
CH431TY,135877,Wirral,344,6905,3446905,Birkenhead High School Academy,86 Devonshire Place,NaN,NaN,Prenton,...,3.0,19.0,Girls,Does not apply,Non-selective,Outstanding,14-10-2015,53.38756,-3.05055,CH431TY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B109HH,147201,Birmingham,330,4035,3304035,"Eden Girls' Leadership Academy, Birmingham",256 Hob Moor Road,NaN,NaN,Birmingham,...,11.0,16.0,Girls,Muslim,Non-selective,NaN,NaN,52.47147,-1.83050,B109HH
NW72EU,147238,Barnet,302,4014,3024014,Hasmonean High School for Girls,2 - 4 Page Street,Mill Hill,NaN,London,...,11.0,18.0,Girls,Jewish,NaN,NaN,NaN,51.60368,-0.23350,NW72EU
PL46HT,148369,Plymouth,879,4155,8794155,Plymouth High School for Girls,St Lawrence Road,NaN,NaN,Plymouth,...,11.0,18.0,Girls,Does not apply,Selective,NaN,NaN,50.37915,-4.13612,PL46HT
B314BP,148684,Birmingham,330,4187,3304187,King Edward VI Northfield School for Girls,Turves Green,Northfield,NaN,Birmingham,...,11.0,16.0,Girls,Does not apply,Non-selective,NaN,NaN,52.40019,-1.96892,B314BP
CR95AS,149347,Croydon,306,5405,3065405,Coloma Convent Girls' School,Upper Shirley Road,NaN,NaN,Croydon,...,11.0,18.0,Girls,Roman Catholic,Non-selective,NaN,NaN,51.36932,-0.05291,CR95AS

In [47]:
import plotly.graph_objects as go
mapbox_access_token = 'pk.eyJ1Ijoia2FtcmFubXVuYXdhciIsImEiOiJjbGMzZmlyeGMwZGw3M29wZ2psNXFpNzY0In0.zdSxz7Y95p97pUh-rWZvIA'

In [49]:

fig = go.Figure()

fig.add_trace(go.Scattermapbox(
        lat=girlschool.lat,
        lon=girlschool.long,
        mode='markers',
        marker=go.scattermapbox.Marker(
            size=17,
            color='rgb(52, 155, 235)',
            opacity=0.9
        ),
        text=girlschool.SCHNAME,
        hoverinfo='text'
    ))



fig.update_layout(
    title=' Girls Academy schools',
    autosize=True,
    hovermode='closest',
    showlegend=False,
    mapbox=dict(
        accesstoken=mapbox_access_token,
        bearing=0,
        center=dict(
            lat=51,
            lon=-0
        ),
        pitch=0,
        zoom=3,
        style='light'
    ),
)
fig.show(renderer="browser")